/* AUTO-GENERADO por Web/scripts/build-catalogos-construccion.mjs — NO editar a mano.
   Fuente: DESARROLLO/EETT y Presupuesto/CATALOGO_PRESUPUESTO_2.0.md */
export interface PartidaPresupuesto { id: string; cap: number; partida: string; unidad: string; puUF: number; cantDef: 'm2' | 'glob' | ''; activaSi: string; }
export const CATALOGO_PRESUPUESTO: PartidaPresupuesto[] = [
  { id: "1.1", cap: 1, partida: "Instalación de faenas y construcciones provisorias", unidad: "glob", puUF: 80, cantDef: "glob", activaSi: "siempre" },
  { id: "1.2", cap: 1, partida: "Empalmes provisorios de servicios", unidad: "glob", puUF: 25, cantDef: "glob", activaSi: "naturaleza ∈ {obra_nueva, ampliacion_mayor, reconstruccion}" },
  { id: "1.3", cap: 1, partida: "Cierro provisorio y letrero de obra", unidad: "ml", puUF: 0.45, cantDef: "", activaSi: "naturaleza ≠ obra_menor" },
  { id: "1.4", cap: 1, partida: "Trazado, niveles y replanteo", unidad: "m2", puUF: 0.12, cantDef: "m2", activaSi: "siempre" },
  { id: "2.1", cap: 2, partida: "Despeje y limpieza del terreno", unidad: "m2", puUF: 0.15, cantDef: "m2", activaSi: "naturaleza ∈ {obra_nueva, reconstruccion} OR urbanizacion incluye algo" },
  { id: "2.2", cap: 2, partida: "Movimiento de tierras (exc., relleno, comp.)", unidad: "m3", puUF: 0.55, cantDef: "", activaSi: "fundaciones = sí AND naturaleza ∈ {obra_nueva, ampliacion_mayor, reconstruccion}" },
  { id: "2.3", cap: 2, partida: "Muros de contención y estabilización", unidad: "m3", puUF: 9.5, cantDef: "", activaSi: "fundaciones = sí AND naturaleza ∈ {obra_nueva, reconstruccion}" },
  { id: "3.1", cap: 3, partida: "Demoliciones y desarmes", unidad: "m2", puUF: 0.9, cantDef: "", activaSi: "demoliciones = sí" },
  { id: "3.2", cap: 3, partida: "Retiro de artefactos e instalaciones", unidad: "glob", puUF: 12, cantDef: "glob", activaSi: "demoliciones = sí AND (banos = sí OR instalaciones no vacío)" },
  { id: "3.3", cap: 3, partida: "Retiro de escombros", unidad: "m3", puUF: 0.55, cantDef: "", activaSi: "demoliciones = sí" },
  { id: "4.1", cap: 4, partida: "Fundaciones (hormigón + acero + emplant.)", unidad: "m2", puUF: 4.8, cantDef: "m2", activaSi: "fundaciones = sí" },
  { id: "4.2", cap: 4, partida: "Sobrecimientos y radier", unidad: "m2", puUF: 1.2, cantDef: "m2", activaSi: "radier = sí OR fundaciones = sí" },
  { id: "4.3", cap: 4, partida: "Sobrelosas de nivelación", unidad: "m2", puUF: 0.85, cantDef: "", activaSi: "sobrelosa = sí" },
  { id: "4.4", cap: 4, partida: "Estructura resistente vertical (hormigón/alb./metal/madera)", unidad: "m2", puUF: 6.5, cantDef: "m2", activaSi: "naturaleza ∈ {obra_nueva, ampliacion_mayor, reconstruccion}" },
  { id: "4.5", cap: 4, partida: "Losas y entrepisos", unidad: "m2", puUF: 5.2, cantDef: "", activaSi: "naturaleza ∈ {obra_nueva, ampliacion_mayor, reconstruccion} AND estructura incluye {hormigon, metalica}" },
  { id: "4.6", cap: 4, partida: "Estructura de techumbre", unidad: "m2", puUF: 2.4, cantDef: "", activaSi: "techumbre = sí" },
  { id: "4.7", cap: 4, partida: "Cubierta y hojalatería", unidad: "m2", puUF: 2.8, cantDef: "", activaSi: "techumbre = sí" },
  { id: "5.1", cap: 5, partida: "Tabiquería interior", unidad: "m2", puUF: 1.8, cantDef: "", activaSi: "tabiqueria = sí" },
  { id: "5.2", cap: 5, partida: "Revestimiento de muros", unidad: "m2", puUF: 1.4, cantDef: "", activaSi: "rev_muros ≠ solo_obra_gruesa" },
  { id: "5.3", cap: 5, partida: "Cielos", unidad: "m2", puUF: 1.6, cantDef: "", activaSi: "cielos ≠ solo_obra_gruesa" },
  { id: "5.4", cap: 5, partida: "Pavimentos y pisos", unidad: "m2", puUF: 1.5, cantDef: "m2", activaSi: "pisos ≠ solo_obra_gruesa" },
  { id: "5.5", cap: 5, partida: "Puertas", unidad: "un", puUF: 2.5, cantDef: "", activaSi: "puertas no vacío" },
  { id: "5.6", cap: 5, partida: "Ventanas", unidad: "m2", puUF: 3.2, cantDef: "", activaSi: "ventanas no vacío" },
  { id: "5.7", cap: 5, partida: "Pinturas", unidad: "m2", puUF: 0.35, cantDef: "", activaSi: "pinturas = sí" },
  { id: "5.8", cap: 5, partida: "Impermeabilización de recintos húmedos", unidad: "m2", puUF: 0.9, cantDef: "", activaSi: "banos = sí" },
  { id: "5.9", cap: 5, partida: "Mobiliario en obra (cocina, baños, clósets)", unidad: "glob", puUF: 60, cantDef: "glob", activaSi: "mobiliario = sí" },
  { id: "6.1", cap: 6, partida: "Instalación eléctrica", unidad: "m2", puUF: 3.5, cantDef: "m2", activaSi: "instalaciones incluye electrica" },
  { id: "6.2", cap: 6, partida: "Instalación sanitaria", unidad: "m2", puUF: 2.8, cantDef: "m2", activaSi: "instalaciones incluye sanitaria OR banos = sí" },
  { id: "6.3", cap: 6, partida: "Climatización y ventilación", unidad: "m2", puUF: 4.5, cantDef: "m2", activaSi: "instalaciones incluye climatizacion" },
  { id: "6.4", cap: 6, partida: "Gas", unidad: "glob", puUF: 40, cantDef: "glob", activaSi: "instalaciones incluye gas" },
  { id: "6.5", cap: 6, partida: "Corrientes débiles", unidad: "m2", puUF: 1.2, cantDef: "m2", activaSi: "instalaciones incluye corrientes_debiles" },
  { id: "6.6", cap: 6, partida: "Red de incendio", unidad: "m2", puUF: 1.8, cantDef: "m2", activaSi: "instalaciones incluye incendio" },
  { id: "6.7", cap: 6, partida: "Transporte vertical", unidad: "un", puUF: 900, cantDef: "", activaSi: "instalaciones incluye transporte_vertical" },
  { id: "7.1", cap: 7, partida: "Cumplimiento norma térmica (aislaciones, complejos)", unidad: "m2", puUF: 1.1, cantDef: "m2", activaSi: "cumplir_termica = sí" },
  { id: "7.2", cap: 7, partida: "Resistencia al fuego y protección pasiva", unidad: "m2", puUF: 0.8, cantDef: "m2", activaSi: "resistencia_fuego = sí" },
  { id: "8.1", cap: 8, partida: "Pavimentos exteriores", unidad: "m2", puUF: 1.3, cantDef: "", activaSi: "urbanizacion incluye pav_exterior" },
  { id: "8.2", cap: 8, partida: "Áreas verdes y paisajismo", unidad: "m2", puUF: 0.7, cantDef: "", activaSi: "urbanizacion incluye areas_verdes" },
  { id: "8.3", cap: 8, partida: "Cierros perimetrales definitivos", unidad: "ml", puUF: 4, cantDef: "", activaSi: "urbanizacion incluye cierros" },
  { id: "8.4", cap: 8, partida: "Evacuación de aguas lluvias exteriores", unidad: "glob", puUF: 50, cantDef: "glob", activaSi: "urbanizacion incluye aguas_lluvia" },
];
